name: Build, Test

on:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            ### Setup action's dependencies
            - uses: actions/checkout@v2 # checkout repo
            - uses: actions/setup-node@v2 # install node 15.5.0 and yarn
              with:
                  node-version: '15.5.0'

            ### Build
            - name: Install Dependencies
              run: yarn install
            - name: Build
              run: yarn build

            ### Testing
            - name: Test
              run: yarn test
